site_name: knowledgeRAG
repo_url: https://github.com/jdiez/knowledgeRAG
site_url: https://jdiez.github.io/knowledgeRAG
site_description: Chat RAG for knowledge bases.
site_author: Javier Díez Pérez
edit_uri: edit/main/docs/
repo_name: jdiez/knowledgeRAG
copyright: Maintained by <a href="https://jdiez.com">jdiez</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/knowledgerag"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jdiez/knowledgeRAG
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/knowledgeRAG

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
